version: '3.8'
services:
  postgres_db:
    image: postgres:16
    container_name: crm_postgres_db
    restart: always
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
      POSTGRES_DB: crm_db
    ports:
      - '5499:5432'
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

volumes:
  postgres_db_data:
