services:
  - type: web
    name: nestjs-crm-lite-api
    env: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: sh start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SALT_ROUNDS
        value: 10
    healthCheckPath: /health
